export const LUDWIG_UI_TOOL_NAMES = ['provideInspirationImageUI', 'provideFloorPlanUI'] as const;

export const productCategoryIcons: Record<string, string> = {
	'Arm Chair': 'icon-[mdi--sofa-single-outline]',
	Artwork: 'icon-[mdi--image-frame]',
	'Baking Dish': 'icon-[mdi--pot-outline]',
	'Bamboo Flooring': 'icon-[mdi--texture-box]',
	'Bar Cart': 'icon-[mdi--cart-outline]',
	'Bar Stool': 'icon-[mdi--stool-outline]',
	'Bar Table': 'icon-[mdi--table-furniture]',
	'Bath Linens': 'icon-[mdi--cloth-outline]',
	'Bathroom Accessories': 'icon-[mdi--shower]',
	Bed: 'icon-[mdi--bed-king-outline]',
	Bedding: 'icon-[mdi--bed-outline]',
	'Bedroom Vanity': 'icon-[mdi--mirror-variant]',
	Bench: 'icon-[mdi--bench-back]',
	Blind: 'icon-[mdi--blinds-horizontal-closed]',
	Bookcase: 'icon-[mdi--bookshelf]',
	Bowl: 'icon-[mdi--bowl-outline]',
	Broom: 'icon-[mdi--broom]',
	Brush: 'icon-[mdi--brush-outline]',
	Cabinet: 'icon-[mdi--cupboard-outline]',
	'Can Opener': 'icon-[mdi--bottle-wine-outline]',
	Carpet: 'icon-[mdi--rug]',
	'Ceiling Lamp': 'icon-[mdi--ceiling-light-outline]',
	'Ceiling Mirror': 'icon-[mdi--mirror-rectangle]',
	'Chaise Lounge': 'icon-[mdi--chair-accent-outline]',
	Chest: 'icon-[mdi--treasure-chest-outline]',
	'Coat Rack': 'icon-[mdi--hanger]',
	'Coffee Maker': 'icon-[mdi--coffee-maker-outline]',
	'Coffee Table': 'icon-[mdi--table-furniture]',
	Colander: 'icon-[mdi--pot-outline]',
	'Concrete Flooring': 'icon-[mdi--texture-box]',
	'Console Table': 'icon-[mdi--table-furniture]',
	'Cookie Sheet': 'icon-[mdi--cookie]',
	Cookware: 'icon-[mdi--pot-steam-outline]',
	'Cork Flooring': 'icon-[mdi--texture]',
	Corkscrew: 'icon-[mdi--bottle-wine-outline]',
	Counter: 'icon-[mdi--countertop-outline]',
	'Counter Stool': 'icon-[mdi--stool-outline]',
	Cup: 'icon-[mdi--cup-outline]',
	Curtain: 'icon-[mdi--curtains]',
	'Curtain Panels': 'icon-[mdi--window-open-variant]',
	'Curtain Rod': 'icon-[mdi--window-minimize]',
	'Cutting Board': 'icon-[mdi--square-opacity]',
	Desk: 'icon-[mdi--desk]',
	'Desk Chair': 'icon-[mdi--chair-rolling]',
	'Dining Chair': 'icon-[mdi--table-chair]',
	'Dining Table': 'icon-[mdi--table-picnic]',
	Dinnerware: 'icon-[mdi--silverware]',
	Dresser: 'icon-[mdi--dresser-outline]',
	Dustpan: 'icon-[mdi--delete-sweep-outline]',
	'Engineered Wood': 'icon-[mdi--texture-box]',
	'Entry Hook': 'icon-[mdi--hanger]',
	Fixture: 'icon-[mdi--ceiling-light-outline]',
	'Floor Lamp': 'icon-[mdi--floor-lamp-outline]',
	Fork: 'icon-[mdi--silverware-fork]',
	Grater: 'icon-[mdi--cheese-off]',
	'Hair Dryer': 'icon-[mdi--hair-dryer-outline]',
	Hanger: 'icon-[mdi--hanger]',
	'Hardwood Flooring': 'icon-[mdi--view-grid-compact]',
	'Head Board': 'icon-[mdi--bed-queen-outline]',
	Iron: 'icon-[mdi--iron-outline]',
	'Ironing Board': 'icon-[mdi--iron-board]',
	Kettle: 'icon-[mdi--kettle-outline]',
	'King Mattress': 'icon-[mdi--bed-double]',
	'Kitchen Tool': 'icon-[mdi--silverware]',
	Knife: 'icon-[mdi--knife]',
	Ladle: 'icon-[mdi--silverware-spoon]',
	'Laminate Flooring': 'icon-[mdi--texture]',
	Linoleum: 'icon-[mdi--texture-box]',
	Loveseat: 'icon-[mdi--sofa-outline]',
	Nightstand: 'icon-[mdi--kazakhstani-tenge]',
	Ottoman: 'icon-[mdi--chair]',
	'Pancake Turner': 'icon-[mdi--silverware-spoon]',
	'Pendant Light': 'icon-[mdi--ceiling-light-outline]',
	Pillow: 'icon-[mdi--panorama-horizontal-outline]',
	Pitcher: 'icon-[mdi--glass-mug]',
	Plant: 'icon-[mdi--flower-outline]',
	Planter: 'icon-[mdi--pot-outline]',
	Plate: 'icon-[mdi--bowl-outline]',
	Plunger: 'icon-[mdi--toothbrush-electric]',
	Potholder: 'icon-[mdi--pot-outline]',
	'Pots & Vases': 'icon-[mdi--pot-outline]',
	'Queen Mattress': 'icon-[mdi--bed-queen-outline]',
	Rack: 'icon-[mdi--train-track]',
	'Roast Pan': 'icon-[mdi--pot-steam-outline]',
	Rug: 'icon-[mdi--rug]',
	'Rug Pad': 'icon-[mdi--texture]',
	'Salad Plate': 'icon-[mdi--bowl-mix-outline]',
	'Salt & Pepper Shaker': 'icon-[mdi--shaker-outline]',
	Sconce: 'icon-[mdi--wall-sconce-outline]',
	Screen: 'icon-[mdi--monitor-screenshot]',
	Sculpture: 'icon-[mdi--historic]',
	Sectional: 'icon-[mdi--sofa-outline]',
	Shelf: 'icon-[mdi--file-cabinet]',
	'Shelving Unit': 'icon-[mdi--bookshelf]',
	'Side Table': 'icon-[mdi--table-furniture]',
	Sideboard: 'icon-[mdi--cupboard-outline]',
	'Silverware Tray': 'icon-[mdi--silverware]',
	Skillet: 'icon-[mdi--pot-steam-outline]',
	'Small Appliance': 'icon-[mdi--blender-outline]',
	Sofa: 'icon-[mdi--sofa-outline]',
	'Sofa Bed': 'icon-[mdi--seat-flat-angled]',
	'Sound Machine': 'icon-[mdi--voicemail]',
	'Soup Bowl': 'icon-[mdi--bowl-outline]',
	'Speaker Dock': 'icon-[mdi--headset-dock]',
	Spoon: 'icon-[mdi--silverware-spoon]',
	'Standing Mirror': 'icon-[mdi--mirror-rectangle]',
	Stands: 'icon-[mdi--table-furniture]',
	'Stone Flooring': 'icon-[mdi--texture-box]',
	'Storage Cabinet': 'icon-[mdi--cupboard-outline]',
	'Table Lamp': 'icon-[mdi--lamp-outline]',
	Tablecloth: 'icon-[mdi--cloth-outline]',
	'Throw Blanket': 'icon-[mdi--invoice-outline]',
	'Throw Pillow': 'icon-[mdi--decagram-outline]',
	Tile: 'icon-[mdi--texture-box]',
	Toaster: 'icon-[mdi--toaster-oven]',
	Tongs: 'icon-[mdi--silverware]',
	Towel: 'icon-[mdi--invoice-multiple-outline]',
	Tray: 'icon-[mdi--tray]',
	Tumbler: 'icon-[mdi--cup-outline]',
	TV: 'icon-[mdi--tv]',
	'TV Media Console': 'icon-[mdi--sideboard]',
	'TV Wall Mount': 'icon-[mdi--television-guide]',
	'Twin Mattress': 'icon-[mdi--bed-single-outline]',
	Utensils: 'icon-[mdi--silverware]',
	Vanity: 'icon-[mdi--mirror]',
	'Vanity Light': 'icon-[mdi--vanity-light]',
	'Vegetable Peeler': 'icon-[mdi--fruit-citrus]',
	'Vinyl Flooring': 'icon-[mdi--texture]',
	'Wall Mirror': 'icon-[mdi--mirror-variant]',
	Wallpaper: 'icon-[mdi--wallpaper]',
	Wardrobe: 'icon-[mdi--wardrobe-outline]',
	'Waste basket': 'icon-[mdi--delete-outline]',
	Whisk: 'icon-[mdi--pot-mix-outline]',
	'Wine Glass': 'icon-[mdi--glass-wine]'
};
