import type { ProductCategory } from '$lib/types';

export const LUDWIG_UI_TOOL_NAMES = ['provideInspirationImageUI', 'provideFloorPlanUI'] as const;

export const productCategories = [
	'Arm Chair',
	'Artwork',
	'Baking Dish',
	'Bar Cart',
	'Bar Stool',
	'Bar Table',
	'Bath Linens',
	'Bathroom Accessory',
	'Ornament',
	'Bathtub',
	'Bed',
	'Bedding',
	'Bedroom Vanity',
	'Bench',
	'Blind',
	'Bookcase',
	'Cabinet',
	'Carpet',
	'Ceiling Lamp',
	'Ceiling Mirror',
	'Chaise Lounge',
	'Chest',
	'Coat Rack',
	'Coffee Table',
	'Console Table',
	'Cookware',
	'Counter',
	'Counter Stool',
	'Crib',
	'Crib Mattress',
	'Crib Bed',
	'Crib Bedding',
	'Curtain',
	'Desk',
	'Desk Chair',
	'Dining Chair',
	'Dining Table',
	'Dinnerware',
	'Dresser',
	'Entry Hook',
	'Floor Lamp',
	'Kettle',
	'King Mattress',
	'Kitchen Accessory',
	'LED Light',
	'Loveseat',
	'Nightstand',
	'Ottoman',
	'Pendant Light',
	'Pillow',
	'Plant',
	'Planter',
	'Artificial Plant',
	'Queen Mattress',
	'Rack',
	'Rug',
	'Sconce',
	'Sculpture',
	'Sectional',
	'Shelf',
	'Shelving Unit',
	'Shower Curtain',
	'Side Table',
	'Sideboard',
	'Sofa',
	'Sofa Bed',
	'Standing Mirror',
	'Stands',
	'Storage Cabinet',
	'Table Lamp',
	'Tablecloth',
	'Throw Blanket',
	'Throw Pillow',
	'TV Media Console',
	'Twin Mattress',
	'Vanity',
	'Vanity Light',
	'Wall Mirror',
	'Wardrobe',
	'Waste basket',
	'Outdoor Arm Chair',
	'Outdoor Rug',
	'Outdoor Dining Chair',
	'Outdoor Chair',
	'Outdoor Coffee Table',
	'Outdoor Dining Table',
	'Outdoor Fire Pit',
	'Outdoor Lounger',
	'Outdoor Side Table',
	'Outdoor Sofa',
	'Outdoor Throw Pillow',
	'Outdoor Umbrella',
	'Outdoor Light',
	'Outdoor Lantern',
	'Outdoor Table',
	'Outdoor Table Lamp',
	'Outdoor LED Light',
	'Outdoor Ceiling Lamp'
] as const;

export const productStyles = [
	'Art Deco',
	'Biophilic',
	'Bohemian',
	'Brutalism',
	'Coastal',
	'Colonial',
	'Contemporary',
	'Craftsman',
	'Eclectic',
	'French Country',
	'Hollywood Glamour',
	'Industrial',
	'Japandi',
	'Luxury',
	'Maximalist',
	'Mediterranean',
	'Mid-Century Modern',
	'Minimalist',
	'Modern',
	'Modern Farmhouse',
	'Neoclassical',
	'Neutral',
	'Rustic',
	'Scandinavian',
	'Shabby Chic',
	'Southwestern',
	'Traditional',
	'Transitional',
	'Tudor',
	'Victorian',
	'Vintage'
] as const;

export const productCategoryIcons: Record<ProductCategory, string> = {
	'Arm Chair': 'icon-[mdi--sofa-single-outline]',
	Artwork: 'icon-[mdi--image-frame]',
	'Baking Dish': 'icon-[mdi--pot-outline]',
	'Bar Cart': 'icon-[mdi--cart-outline]',
	'Bar Stool': 'icon-[mdi--stool-outline]',
	'Bar Table': 'icon-[mdi--table-furniture]',
	'Bath Linens': 'icon-[mdi--cloth-outline]',
	Bed: 'icon-[mdi--bed-king-outline]',
	Bedding: 'icon-[mdi--bed-outline]',
	'Bedroom Vanity': 'icon-[mdi--mirror-variant]',
	Bench: 'icon-[mdi--bench-back]',
	Blind: 'icon-[mdi--blinds-horizontal-closed]',
	Bookcase: 'icon-[mdi--bookshelf]',
	Cabinet: 'icon-[mdi--cupboard-outline]',
	Carpet: 'icon-[mdi--rug]',
	'Ceiling Lamp': 'icon-[mdi--ceiling-light-outline]',
	'Ceiling Mirror': 'icon-[mdi--mirror-rectangle]',
	'Chaise Lounge': 'icon-[mdi--chair-accent-outline]',
	Chest: 'icon-[mdi--treasure-chest-outline]',
	'Coat Rack': 'icon-[mdi--hanger]',
	'Coffee Table': 'icon-[mdi--table-furniture]',
	'Console Table': 'icon-[mdi--table-furniture]',
	Cookware: 'icon-[mdi--pot-steam-outline]',
	Counter: 'icon-[mdi--countertop-outline]',
	'Counter Stool': 'icon-[mdi--stool-outline]',
	Curtain: 'icon-[mdi--curtains]',
	Desk: 'icon-[mdi--desk]',
	'Desk Chair': 'icon-[mdi--chair-rolling]',
	'Dining Chair': 'icon-[mdi--table-chair]',
	'Dining Table': 'icon-[mdi--table-picnic]',
	Dinnerware: 'icon-[mdi--silverware]',
	Dresser: 'icon-[mdi--dresser-outline]',
	'Entry Hook': 'icon-[mdi--hanger]',
	'Floor Lamp': 'icon-[mdi--floor-lamp-outline]',
	Kettle: 'icon-[mdi--kettle-outline]',
	'King Mattress': 'icon-[mdi--bed-double]',
	Loveseat: 'icon-[mdi--sofa-outline]',
	Nightstand: 'icon-[mdi--kazakhstani-tenge]',
	Ottoman: 'icon-[mdi--chair]',
	'Pendant Light': 'icon-[mdi--ceiling-light-outline]',
	Pillow: 'icon-[mdi--panorama-horizontal-outline]',
	Plant: 'icon-[mdi--flower-outline]',
	Planter: 'icon-[mdi--pot-outline]',
	'Queen Mattress': 'icon-[mdi--bed-queen-outline]',
	Rack: 'icon-[mdi--train-track]',
	Rug: 'icon-[mdi--rug]',
	Sconce: 'icon-[mdi--wall-sconce-outline]',
	Sculpture: 'icon-[mdi--historic]',
	Sectional: 'icon-[mdi--sofa-outline]',
	Shelf: 'icon-[mdi--file-cabinet]',
	'Shelving Unit': 'icon-[mdi--bookshelf]',
	'Side Table': 'icon-[mdi--table-furniture]',
	Sideboard: 'icon-[mdi--cupboard-outline]',
	Sofa: 'icon-[mdi--sofa-outline]',
	'Sofa Bed': 'icon-[mdi--seat-flat-angled]',
	'Standing Mirror': 'icon-[mdi--mirror-rectangle]',
	Stands: 'icon-[mdi--table-furniture]',
	'Storage Cabinet': 'icon-[mdi--cupboard-outline]',
	'Table Lamp': 'icon-[mdi--lamp-outline]',
	Tablecloth: 'icon-[mdi--cloth-outline]',
	'Throw Blanket': 'icon-[mdi--invoice-outline]',
	'Throw Pillow': 'icon-[mdi--decagram-outline]',
	'TV Media Console': 'icon-[mdi--sideboard]',
	'Twin Mattress': 'icon-[mdi--bed-single-outline]',
	Vanity: 'icon-[mdi--mirror]',
	'Vanity Light': 'icon-[mdi--vanity-light]',
	'Wall Mirror': 'icon-[mdi--mirror-variant]',
	Wardrobe: 'icon-[mdi--wardrobe-outline]',
	'Waste basket': 'icon-[mdi--delete-outline]',
	'Outdoor Arm Chair': 'icon-[mdi--sofa-single-outline]',
	'Outdoor Rug': 'icon-[mdi--rug]',
	'Outdoor Dining Chair': 'icon-[mdi--table-chair]',
	'Outdoor Chair': 'icon-[mdi--chair-accent-outline]',
	'Outdoor Coffee Table': 'icon-[mdi--table-furniture]',
	'Outdoor Dining Table': 'icon-[mdi--table-picnic]',
	'Outdoor Fire Pit': 'icon-[mdi--fireplace]',
	'Outdoor Lounger': 'icon-[mdi--car-child-seat]',
	'Outdoor Side Table': 'icon-[mdi--table-furniture]',
	'Outdoor Sofa': 'icon-[mdi--sofa-single-outline]',
	'Outdoor Throw Pillow': 'icon-[mdi--decagram-outline]',
	'Outdoor Umbrella': 'icon-[mdi--umbrella-outline]',
	'Bathroom Accessory': 'icon-[mdi--shower-head]',
	Ornament: 'icon-[mdi--ornament]',
	Bathtub: 'icon-[mdi--bathtub-outline]',
	Crib: 'icon-[mdi--crib]',
	'Crib Mattress': 'icon-[mdi--rectangle]',
	'Crib Bed': 'icon-[mdi--bed-outline]',
	'Crib Bedding': 'icon-[mdi--clothes-hanger]',
	'Kitchen Accessory': 'icon-[mdi--kitchen-counter-outline]',
	'LED Light': 'icon-[mdi--led-outline]',
	'Artificial Plant': 'icon-[mdi--flower-tulip-outline]',
	'Shower Curtain': 'icon-[mdi--curtains]',
	'Outdoor Light': 'icon-[mdi--post-light]',
	'Outdoor Lantern': 'icon-[mdi--bulkhead-light]',
	'Outdoor Table': 'icon-[mdi--table-picnic]',
	'Outdoor Table Lamp': 'icon-[mdi--lamp-outline]',
	'Outdoor LED Light': 'icon-[mdi--led-strip]',
	'Outdoor Ceiling Lamp': 'icon-[mdi--ceiling-light-outline]'
};
