export const enum QueryParams {
	AUTH_STEP = 'aus',
	AUTH_REDIRECT_URL = 'aru',
	FORCE_REFRESH_TOKEN = 'frt',
	LUDWIG_PAGE_DESIGN_VIEW = 'lpdv',
	LUDWIG_CHAT_ID = 'lcid',
	ACTIVE_DESIGN_ASSET_TAB = 'dat',
	FILE_UPLOAD_TYPE = 'fut',
	PRODUCT_FILTERS = 'pf',
	PRODUCT_SORT_OPTIONS = 'pso',
	DESIGN_CURRENCY_CODE = 'dcc',
	PRODUCT_FULL_TEXT_SEARCH_VALUE = 'pfts',
	APP_ADMIN_ACCESS_TOKEN = 'aat',
	PINTEREST_CALLBACK_REDIRECT_URL = 'picr'
}
