export const productCategories = [
	'Arm Chair',
	'Artwork',
	'Baking Dish',
	'Bar Cart',
	'Bar Stool',
	'Bar Table',
	'Bath Linens',
	'Bathroom Accessory',
	'Ornament',
	'Bathtub',
	'Bed',
	'King Bed',
	'Queen Bed',
	'Twin Bed',
	'Double Bed',
	'Bedding',
	'Bedroom Vanity',
	'Bench',
	'Blind',
	'Bookcase',
	'Cabinet',
	'Carpet',
	'Ceiling Lamp',
	'Ceiling Mirror',
	'Chaise Lounge',
	'Chest',
	'Coat Rack',
	'Coffee Table',
	'Console Table',
	'Cookware',
	'Counter',
	'Counter Stool',
	'Crib',
	'Crib Mattress',
	'Crib Bed',
	'Crib Bedding',
	'Curtain',
	'Desk',
	'Desk Chair',
	'Dining Chair',
	'Dining Table',
	'Dinnerware',
	'Dresser',
	'Entry Hook',
	'Floor Lamp',
	'Kettle',
	'King Mattress',
	'Double Mattress',
	'Twin Mattress',
	'Kitchen Accessory',
	'Cutlery',
	'Bakeware',
	'Kitchen Appliance',
	'LED Light',
	'Loveseat',
	'Nightstand',
	'Ottoman',
	'Pendant Light',
	'Pillow',
	'Plant',
	'Planter',
	'Artificial Plant',
	'Queen Mattress',
	'Rack',
	'Rug',
	'Runner',
	'Sconce',
	'Sculpture',
	'Sectional',
	'Shelf',
	'Shelving Unit',
	'Shower Curtain',
	'Side Table',
	'Sideboard',
	'Sofa',
	'Sofa Bed',
	'Standing Mirror',
	'Stands',
	'Storage Cabinet',
	'Table Lamp',
	'Tablecloth',
	'Throw Blanket',
	'Throw Pillow',
	'TV Media Console',
	'Twin Mattress',
	'Vanity',
	'Vanity Light',
	'Wall Mirror',
	'Wardrobe',
	'Waste basket',
	'Outdoor Arm Chair',
	'Outdoor Rug',
	'Outdoor Dining Chair',
	'Outdoor Chair',
	'Outdoor Coffee Table',
	'Outdoor Dining Table',
	'Outdoor Fire Pit',
	'Outdoor Lounger',
	'Outdoor Side Table',
	'Outdoor Sofa',
	'Outdoor Throw Pillow',
	'Outdoor Umbrella',
	'Outdoor Light',
	'Outdoor Lantern',
	'Outdoor Table',
	'Outdoor Table Lamp',
	'Outdoor LED Light',
	'Outdoor Ceiling Lamp',
	'Outdoor Lamp',
	'Door',
	'Tile',
	'Tabletop Decor',
	'Vase',
	'Bookends',
	'Wall Art',
	'Wallpaper',
	'Seasonal Decor'
] as const;

export const productStyles = [
	'Art Deco',
	'Biophilic',
	'Bohemian',
	'Brutalism',
	'Coastal',
	'Colonial',
	'Contemporary',
	'Craftsman',
	'Eclectic',
	'French Country',
	'Hollywood Glamour',
	'Industrial',
	'Japandi',
	'Luxury',
	'Maximalist',
	'Mediterranean',
	'Mid-Century Modern',
	'Minimalist',
	'Modern',
	'Modern Farmhouse',
	'Neoclassical',
	'Neutral',
	'Rustic',
	'Scandinavian',
	'Shabby Chic',
	'Southwestern',
	'Traditional',
	'Transitional',
	'Tudor',
	'Victorian',
	'Vintage'
] as const;
