import { ProductCategory } from '../product/type';
import { SpaceType } from './type';

export const spaceTypes = [
	'Attic',
	'Basement',
	'Bathroom',
	'Bedroom',
	'Classroom',
	'Dining Room',
	'Entryway',
	'Event Space',
	'Exercise Room',
	'Kitchen',
	'Laundry Room',
	'Library',
	'Living Room',
	'Lobby',
	'Locker Room',
	'Lounge',
	'Media Room',
	'Medical Room',
	'Meeting Room',
	'Mudroom',
	'Office',
	'Outdoor Space',
	'Spa',
	'Walk-in Closet'
] as const;

export const spaceTypeProductCategories: Record<
	SpaceType,
	{
		all: ProductCategory[];
		recommended: ProductCategory[];
	}
> = {
	Attic: {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bench',
			'Blind',
			'Bookcase',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chest',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Laminate Flooring',
			'Linoleum',
			'Rug',
			'Rug Pad',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Table Lamp',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Wardrobe',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Shelf',
			'Storage Cabinet',
			'Rug',
			'Ceiling Lamp',
			'Floor Lamp',
			'Bench',
			'Arm Chair',
			'Curtain',
			'Standing Mirror',
			'Plant'
		]
	},
	Basement: {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bar Cart',
			'Bar Stool',
			'Bar Table',
			'Bench',
			'Bookcase',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Coffee Maker',
			'Coffee Table',
			'Concrete Flooring',
			'Console Table',
			'Cork Flooring',
			'Counter',
			'Counter Stool',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Desk',
			'Desk Chair',
			'Dresser',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Kettle',
			'Laminate Flooring',
			'Linoleum',
			'Loveseat',
			'Ottoman',
			'Pendant Light',
			'Pillow',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sideboard',
			'Small Appliance',
			'Sofa',
			'Sofa Bed',
			'Sound Machine',
			'Speaker Dock',
			'Table Lamp',
			'Tile',
			'Toaster',
			'TV',
			'TV Media Console',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Waste basket',
			'Wine Glass',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Sectional',
			'Sofa',
			'Coffee Table',
			'Side Table',
			'TV Media Console',
			'Rug',
			'Floor Lamp',
			'Sconce',
			'Ottoman',
			'Throw Blanket'
		]
	},
	Bathroom: {
		all: [
			'Artwork',
			'Bath Linens',
			'Bathroom Accessories',
			'Cabinet',
			'Ceiling Lamp',
			'Ceiling Mirror',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Fixture',
			'Floor Lamp',
			'Hair Dryer',
			'Linoleum',
			'Pendant Light',
			'Plunger',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Table Lamp',
			'Tile',
			'Towel',
			'Vanity',
			'Vanity Light',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Waste basket',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Vanity',
			'Vanity Light',
			'Wall Mirror',
			'Bathroom Accessories',
			'Bath Linens',
			'Towel',
			'Rug',
			'Curtain',
			'Waste basket'
		]
	},
	Bedroom: {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bed',
			'Bedding',
			'Bench',
			'Blind',
			'Bookcase',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Chest',
			'Console Table',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Dresser',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Head Board',
			'King Mattress',
			'Laminate Flooring',
			'Nightstand',
			'Ottoman',
			'Pendant Light',
			'Pillow',
			'Queen Mattress',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sofa Bed',
			'Sound Machine',
			'Standing Mirror',
			'Table Lamp',
			'Throw Blanket',
			'Throw Pillow',
			'TV',
			'TV Media Console',
			'TV Wall Mount',
			'Twin Mattress',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Wardrobe',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Bed',
			'Nightstand',
			'Dresser',
			'Wardrobe',
			'Rug',
			'Table Lamp',
			'Curtain',
			'Standing Mirror',
			'Pillow',
			'Artwork'
		]
	},
	Classroom: {
		all: [
			'Artwork',
			'Bench',
			'Blind',
			'Bookcase',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Console Table',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Desk',
			'Desk Chair',
			'Engineered Wood',
			'Floor Lamp',
			'Laminate Flooring',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Table Lamp',
			'TV',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wallpaper',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Desk',
			'Desk Chair',
			'Bookcase',
			'Shelving Unit',
			'Ceiling Lamp',
			'Pendant Light',
			'Rug',
			'Artwork',
			'Plant'
		]
	},
	'Dining Room': {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bar Cart',
			'Bar Stool',
			'Bar Table',
			'Bench',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Console Table',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Dining Chair',
			'Dining Table',
			'Dinnerware',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Laminate Flooring',
			'Pendant Light',
			'Plate',
			'Bowl',
			'Soup Bowl',
			'Salad Plate',
			'Cup',
			'Tumbler',
			'Wine Glass',
			'Pitcher',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Sideboard',
			'Table Lamp',
			'Tablecloth',
			'Tray',
			'Utensils',
			'Fork',
			'Spoon',
			'Knife',
			'Ladle',
			'Tongs',
			'Silverware Tray',
			'Salt & Pepper Shaker',
			'Tile',
			'Wall Mirror',
			'Wallpaper',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: ['Dining Table', 'Dining Chair', 'Pendant Light', 'Rug', 'Artwork', 'Plant']
	},
	Entryway: {
		all: [
			'Artwork',
			'Bench',
			'Blind',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Coat Rack',
			'Console Table',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Entry Hook',
			'Floor Lamp',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Table Lamp',
			'Wall Mirror',
			'Wallpaper',
			'Wardrobe',
			'Rack',
			'Waste basket',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: ['Bench', 'Coat Rack', 'Entry Hook', 'Rug', 'Wall Mirror', 'Sconce', 'Plant']
	},
	'Event Space': {
		all: [
			'Arm Chair',
			'Artwork',
			'Bar Cart',
			'Bar Stool',
			'Bar Table',
			'Bench',
			'Carpet',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Coffee Table',
			'Console Table',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Dining Chair',
			'Dining Table',
			'Floor Lamp',
			'Ottoman',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sideboard',
			'Stands',
			'Table Lamp',
			'Tablecloth',
			'Tile',
			'TV',
			'TV Wall Mount',
			'Wallpaper',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Dining Chair',
			'Bar Stool',
			'Bar Table',
			'Stands',
			'Rug',
			'Pendant Light',
			'Sconce',
			'Artwork',
			'Plant'
		]
	},
	'Exercise Room': {
		all: [
			'Bench',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Concrete Flooring',
			'Floor Lamp',
			'Laminate Flooring',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Table Lamp',
			'TV',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wall Mirror',
			'Waste basket',
			'Plant',
			'Planter'
		],
		recommended: ['Standing Mirror', 'Bench', 'Rack', 'Shelf', 'Rug', 'Ceiling Lamp', 'Sconce']
	},
	Kitchen: {
		all: [
			'Artwork',
			'Baking Dish',
			'Bar Stool',
			'Bar Table',
			'Cabinet',
			'Can Opener',
			'Ceiling Lamp',
			'Colander',
			'Concrete Flooring',
			'Cookie Sheet',
			'Cookware',
			'Corkscrew',
			'Counter',
			'Counter Stool',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Cutting Board',
			'Dinnerware',
			'Engineered Wood',
			'Fixture',
			'Floor Lamp',
			'Fork',
			'Grater',
			'Hardwood Flooring',
			'Kettle',
			'Kitchen Tool',
			'Knife',
			'Laminate Flooring',
			'Ladle',
			'Linoleum',
			'Pendant Light',
			'Plate',
			'Bowl',
			'Soup Bowl',
			'Salad Plate',
			'Cup',
			'Tumbler',
			'Wine Glass',
			'Pitcher',
			'Potholder',
			'Rug',
			'Rug Pad',
			'Salt & Pepper Shaker',
			'Sconce',
			'Shelf',
			'Shelving Unit',
			'Silverware Tray',
			'Skillet',
			'Small Appliance',
			'Table Lamp',
			'Tablecloth',
			'Tile',
			'Toaster',
			'Tongs',
			'Tray',
			'Towel',
			'Utensils',
			'Vegetable Peeler',
			'Vinyl Flooring',
			'Wallpaper',
			'Coffee Maker',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Cabinet',
			'Counter',
			'Pendant Light',
			'Bar Stool',
			'Cookware',
			'Knife',
			'Cutting Board',
			'Skillet',
			'Small Appliance',
			'Coffee Maker',
			'Toaster',
			'Dinnerware',
			'Utensils',
			'Plate',
			'Bowl',
			'Kettle',
			'Colander'
		]
	},
	'Laundry Room': {
		all: [
			'Artwork',
			'Broom',
			'Brush',
			'Cabinet',
			'Ceiling Lamp',
			'Counter',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Dustpan',
			'Floor Lamp',
			'Hanger',
			'Iron',
			'Ironing Board',
			'Laminate Flooring',
			'Linoleum',
			'Pendant Light',
			'Rack',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Shelf',
			'Shelving Unit',
			'Storage Cabinet',
			'Table Lamp',
			'Tile',
			'Towel',
			'Vinyl Flooring',
			'Wallpaper',
			'Waste basket',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Storage Cabinet',
			'Counter',
			'Hanger',
			'Ironing Board',
			'Rack',
			'Shelving Unit',
			'Towel',
			'Ceiling Lamp',
			'Waste basket'
		]
	},
	Library: {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bench',
			'Blind',
			'Bookcase',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Coffee Table',
			'Console Table',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Desk',
			'Desk Chair',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Laminate Flooring',
			'Loveseat',
			'Ottoman',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sofa',
			'Standing Mirror',
			'Table Lamp',
			'TV',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Bookcase',
			'Arm Chair',
			'Sofa',
			'Desk',
			'Desk Chair',
			'Rug',
			'Floor Lamp',
			'Table Lamp',
			'Artwork',
			'Plant'
		]
	},
	'Living Room': {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bench',
			'Blind',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Coffee Table',
			'Console Table',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Laminate Flooring',
			'Loveseat',
			'Ottoman',
			'Pendant Light',
			'Pillow',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sideboard',
			'Sofa',
			'Sofa Bed',
			'Sound Machine',
			'Speaker Dock',
			'Standing Mirror',
			'Table Lamp',
			'Throw Blanket',
			'Throw Pillow',
			'Tile',
			'TV',
			'TV Media Console',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Stands',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Sofa',
			'Arm Chair',
			'Coffee Table',
			'Side Table',
			'Rug',
			'Floor Lamp',
			'Throw Pillow',
			'Throw Blanket',
			'TV Media Console',
			'Artwork',
			'Plant'
		]
	},
	Lobby: {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bench',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Coffee Table',
			'Console Table',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Laminate Flooring',
			'Loveseat',
			'Ottoman',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sideboard',
			'Sofa',
			'Standing Mirror',
			'Table Lamp',
			'Tile',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Storage Cabinet',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Sofa',
			'Arm Chair',
			'Bench',
			'Coffee Table',
			'Rug',
			'Pendant Light',
			'Sconce',
			'Console Table',
			'Artwork',
			'Plant',
			'Sculpture'
		]
	},
	'Locker Room': {
		all: [
			'Bath Linens',
			'Bathroom Accessories',
			'Bench',
			'Cabinet',
			'Ceiling Lamp',
			'Ceiling Mirror',
			'Coat Rack',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Floor Lamp',
			'Hanger',
			'Linoleum',
			'Pendant Light',
			'Rack',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Storage Cabinet',
			'Table Lamp',
			'Tile',
			'Towel',
			'Vinyl Flooring',
			'Wall Mirror',
			'Waste basket',
			'Wardrobe',
			'Plant',
			'Planter'
		],
		recommended: [
			'Bench',
			'Rack',
			'Wardrobe',
			'Towel',
			'Wall Mirror',
			'Standing Mirror',
			'Linoleum',
			'Ceiling Lamp',
			'Storage Cabinet'
		]
	},
	Lounge: {
		all: [
			'Arm Chair',
			'Artwork',
			'Bar Cart',
			'Bar Stool',
			'Bar Table',
			'Bench',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Coffee Table',
			'Console Table',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Laminate Flooring',
			'Loveseat',
			'Ottoman',
			'Pendant Light',
			'Pillow',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sideboard',
			'Sofa',
			'Sound Machine',
			'Speaker Dock',
			'Standing Mirror',
			'Table Lamp',
			'Throw Blanket',
			'Throw Pillow',
			'Tile',
			'TV',
			'TV Media Console',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Sofa',
			'Arm Chair',
			'Coffee Table',
			'Side Table',
			'Rug',
			'Pendant Light',
			'Bar Cart',
			'Throw Pillow',
			'Throw Blanket',
			'Artwork',
			'Speaker Dock'
		]
	},
	'Media Room': {
		all: [
			'Arm Chair',
			'Artwork',
			'Bench',
			'Blind',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Coffee Table',
			'Console Table',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Floor Lamp',
			'Loveseat',
			'Ottoman',
			'Pendant Light',
			'Pillow',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sofa',
			'Sofa Bed',
			'Sound Machine',
			'Speaker Dock',
			'Standing Mirror',
			'Table Lamp',
			'Throw Blanket',
			'Throw Pillow',
			'TV',
			'TV Media Console',
			'TV Wall Mount',
			'Wall Mirror',
			'Wallpaper',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Sectional',
			'Sofa',
			'Ottoman',
			'TV Media Console',
			'TV Wall Mount',
			'Sconce',
			'Curtain',
			'Rug',
			'Throw Pillow',
			'Throw Blanket',
			'Speaker Dock'
		]
	},
	'Medical Room': {
		all: [
			'Artwork',
			'Bath Linens',
			'Bed',
			'Bedding',
			'Cabinet',
			'Ceiling Lamp',
			'Ceiling Mirror',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Fixture',
			'Floor Lamp',
			'Hanger',
			'Linoleum',
			'Nightstand',
			'Pendant Light',
			'Pillow',
			'Rack',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Storage Cabinet',
			'Table Lamp',
			'Tile',
			'Towel',
			'Vanity',
			'Vanity Light',
			'Vinyl Flooring',
			'Wall Mirror',
			'Waste basket',
			'Wardrobe',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Bed',
			'Nightstand',
			'Cabinet',
			'Curtain',
			'Ceiling Lamp',
			'Wall Mirror',
			'Storage Cabinet',
			'Towel'
		]
	},
	'Meeting Room': {
		all: [
			'Arm Chair',
			'Artwork',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Console Table',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Desk',
			'Desk Chair',
			'Dining Chair',
			'Dining Table',
			'Floor Lamp',
			'Laminate Flooring',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Sideboard',
			'Table Lamp',
			'Tile',
			'TV',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Dining Table',
			'Dining Chair',
			'Pendant Light',
			'Rug',
			'Console Table',
			'Sideboard',
			'Artwork',
			'Plant'
		]
	},
	Mudroom: {
		all: [
			'Artwork',
			'Bench',
			'Cabinet',
			'Ceiling Lamp',
			'Coat Rack',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Entry Hook',
			'Floor Lamp',
			'Hanger',
			'Laminate Flooring',
			'Linoleum',
			'Pendant Light',
			'Rack',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Storage Cabinet',
			'Table Lamp',
			'Tile',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Wardrobe',
			'Waste basket',
			'Plant',
			'Planter',
			'Pots & Vases',
			'Chest'
		],
		recommended: [
			'Bench',
			'Coat Rack',
			'Entry Hook',
			'Rack',
			'Storage Cabinet',
			'Rug',
			'Tile',
			'Wall Mirror',
			'Waste basket'
		]
	},
	Office: {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bar Cart',
			'Bench',
			'Blind',
			'Bookcase',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Coffee Table',
			'Console Table',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Desk',
			'Desk Chair',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Laminate Flooring',
			'Loveseat',
			'Ottoman',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sofa',
			'Sound Machine',
			'Speaker Dock',
			'Standing Mirror',
			'Table Lamp',
			'Tile',
			'TV',
			'TV Wall Mount',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Storage Cabinet',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Desk',
			'Desk Chair',
			'Bookcase',
			'Shelving Unit',
			'Rug',
			'Floor Lamp',
			'Table Lamp',
			'Sofa',
			'Arm Chair',
			'Artwork',
			'Plant'
		]
	},
	'Outdoor Space': {
		all: [
			'Arm Chair',
			'Artwork',
			'Bar Cart',
			'Bar Stool',
			'Bar Table',
			'Bench',
			'Ceiling Lamp',
			'Chaise Lounge',
			'Coffee Table',
			'Console Table',
			'Counter',
			'Counter Stool',
			'Dining Chair',
			'Dining Table',
			'Floor Lamp',
			'Ottoman',
			'Pendant Light',
			'Planter',
			'Plant',
			'Pots & Vases',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Sculpture',
			'Shelf',
			'Shelving Unit',
			'Side Table',
			'Sideboard',
			'Stands',
			'Table Lamp',
			'Tile',
			'TV',
			'TV Wall Mount',
			'Concrete Flooring',
			'Stone Flooring',
			'Tray',
			'Wine Glass'
		],
		recommended: [
			'Arm Chair',
			'Bench',
			'Chaise Lounge',
			'Dining Table',
			'Dining Chair',
			'Bar Table',
			'Bar Stool',
			'Side Table',
			'Coffee Table',
			'Planter',
			'Rug',
			'Sconce',
			'Sculpture'
		]
	},
	Spa: {
		all: [
			'Artwork',
			'Bath Linens',
			'Bathroom Accessories',
			'Bench',
			'Cabinet',
			'Ceiling Lamp',
			'Ceiling Mirror',
			'Chaise Lounge',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Fixture',
			'Floor Lamp',
			'Linoleum',
			'Ottoman',
			'Pendant Light',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Sculpture',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Table Lamp',
			'Tile',
			'Towel',
			'Vanity',
			'Vanity Light',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Waste basket',
			'Sound Machine',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Chaise Lounge',
			'Vanity',
			'Vanity Light',
			'Towel',
			'Bath Linens',
			'Bathroom Accessories',
			'Sconce',
			'Wall Mirror',
			'Rug',
			'Plant'
		]
	},
	'Walk-in Closet': {
		all: [
			'Arm Chair',
			'Artwork',
			'Bamboo Flooring',
			'Bench',
			'Cabinet',
			'Carpet',
			'Ceiling Lamp',
			'Chest',
			'Cork Flooring',
			'Curtain',
			'Curtain Panels',
			'Curtain Rod',
			'Dresser',
			'Engineered Wood',
			'Floor Lamp',
			'Hardwood Flooring',
			'Hanger',
			'Laminate Flooring',
			'Ottoman',
			'Pendant Light',
			'Rack',
			'Rug',
			'Rug Pad',
			'Sconce',
			'Screen',
			'Shelf',
			'Shelving Unit',
			'Standing Mirror',
			'Storage Cabinet',
			'Table Lamp',
			'Vinyl Flooring',
			'Wall Mirror',
			'Wallpaper',
			'Wardrobe',
			'Plant',
			'Planter',
			'Pots & Vases'
		],
		recommended: [
			'Dresser',
			'Hanger',
			'Rack',
			'Shelving Unit',
			'Standing Mirror',
			'Bench',
			'Rug',
			'Ceiling Lamp'
		]
	}
} as const;
